name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: |
          git submodule update --init --recursive
          forge install

      - name: Build and test
        run: |
          forge build
          forge test
