name: Publish ABIs

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry & deps
        run: |
          ./configure
          curl -L https://foundry.paradigm.xyz | bash
          foundryup
          forge install
          npm ci

      - name: Build & extract ABIs
        run: |
          make build
          make extract-abis

      - name: Upload ABI assets
        uses: softprops/action-gh-release@v1
        with:
          files: abi/*.abi.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
